pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/fearssniper/jenkins-test.git'
        BRANCH = 'main'
        BUILD_SCRIPT = 'build.sh'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                git branch: "${BRANCH}", url: "${REPO_URL}", credentialsId: 'github-token'
            }
        }
        stage('Build') {
            steps {
                echo 'Building...'
                // Set executable permissions for the build script
                sh 'chmod +x ./${BUILD_SCRIPT}'
                // Run the build script
                sh './${BUILD_SCRIPT}'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                // Run a test script or commands
                sh 'echo "Running tests..."'
                sh 'echo "All tests passed!"'
            }
        }
        stage('Archive Artifacts') {
            steps {
                echo 'Archiving artifacts...'
                // Archive any artifacts generated by the build
                archiveArtifacts artifacts: '**/build/**', allowEmptyArchive: true
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Simulate a deployment step
                sh 'echo "Deploy step executed"'
            }
        }
    }

    post {
        always {
            echo 'Cleaning up...'
            // Perform any cleanup steps
            deleteDir() // Deletes the current workspace
        }
        success {
            echo 'Build succeeded!'
            // Example: Send a success notification (echo used here for simplicity)
            sh 'echo "Build and deployment succeeded!"'
        }
        failure {
            echo 'Build failed!'
            // Example: Send a failure notification (echo used here for simplicity)
            sh 'echo "Build and deployment failed!"'
        }
    }
}
